add_requires("lua", "stb")
-- linux
target("test")
set_kind("shared")
add_headerfiles("src/*.hpp")
add_files("src/*.cpp")
add_packages("lua", "stb")
set_languages("c++20")
set_warnings("all")
set_optimize("fastest")
set_targetdir("$(projectdir)/dist/$(mode)")
