on:
  push:
    branches:
    - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: setup xmake          
      uses: xmake-io/github-action-setup-xmake@v1
    - name: Archive build artifacts
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ./build 
